# Generated by Django 3.1.5 on 2021-01-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210128_0215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_Statistics',
            new_name='Player_Statistic',
        ),
    ]
