# Generated by Django 3.1.5 on 2021-01-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210128_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_Statistic',
            new_name='Participation',
        ),
    ]
