# Generated by Django 3.1.5 on 2021-01-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210128_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='side',
            field=models.CharField(choices=[('Host', 'Host'), ('Visitor', 'Visitor')], max_length=200, null=True),
        ),
    ]
