# Generated by Django 3.1.5 on 2021-01-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210128_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='date_played',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
