# Generated by Django 3.1.5 on 2021-01-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210129_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='owner',
        ),
    ]
