# Generated by Django 3.1.5 on 2021-02-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210131_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Half Time', 'Half Time'), ('Abandoned', 'Abandoned'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
